### ISSUE TITLE
Package Elly is required but does not seem to be installed:

### ISSUE THREAD

**Issue by altre** [tanmaykm/Elly.jl#39]
I'm not sure if this package is currently supported in julia 1.1.
I have the problem that the worke nodes don't find the correct package directory.
I've installed julia and elly on all machines and set JULIA_LOAD_PATH to the .julia directory, but I still get the following error:
```
Package Elly [0bb624de-12df-571d-ad84-47aef8b93290] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.

Stacktrace:
 [1] _require(::Base.PkgId) at ./loading.jl:929
 [2] require(::Base.PkgId) at ./loading.jl:858
 [3] require(::Module, ::Symbol) at ./loading.jl:853

        at org.apache.hadoop.util.Shell.runCommand(Shell.java:543)
        at org.apache.hadoop.util.Shell.run(Shell.java:460)
        at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:720)
        at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:211)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by tanmaykm** [comment]
Version ([v0.3.0](https://github.com/JuliaParallel/Elly.jl/releases/tag/v0.3.0)) is now tagged. It should work with Julia 1.x.
